# Generated by Django 3.1.7 on 2021-05-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plmProcessTracking',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('serverName', models.CharField(max_length=100)),
                ('plmStatus', models.CharField(choices=[('Queued', 'Queued'), ('Inprogress', 'Inprogress'), ('Failed', 'Failed'), ('Completed', 'Completed')], max_length=45)),
                ('changeNumber', models.CharField(max_length=100, null=True)),
                ('plmStep', models.CharField(max_length=100, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlmProcessResponse',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('plmStep', models.CharField(max_length=45)),
                ('response', models.TextField(null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('plm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleplm.plmprocesstracking')),
            ],
        ),
    ]
